import os 
import platform
import time

# questions generated by ai 🥱
questions = {
    "What is the capital of France?": {
        "Paris": True,
        "Berlin": False,
        "Madrid": False,
        "Rome": False
    },
    "What is the largest planet in our solar system?": {
        "Earth": False,
        "Mars": False,
        "Jupiter": True,
        "Saturn": False
    },
    "What is the chemical symbol for water?": {
        "H2O": True,
        "CO2": False,
        "O2": False,
        "NaCl": False
    },
    "What is the main ingredient in guacamole?": {
        "Avocado": True,
        "Tomato": False,
        "Onion": False,
        "Pepper": False
    },
    "What is the smallest country in the world?": {
        "Vatican City": True,
        "Monaco": False,
        "San Marino": False,
        "Liechtenstein": False
    },
}

points = 0

def clear_terminal(): # 🤤
    os.system(platform.system() == "Windows" and "cls" or "clear")

def ask_question(question, options: dict[str: bool]):
    clear_terminal()
    
    formatted_options = ""
    
    i = 0
    for a in options:
        formatted_options += f"{i + 1}. {a}\n"
        i += 1

    print("The question is:", question)
    print("Is it:\n" + formatted_options)

def handle_answer(question, options: dict[str: bool]):
    global points
    answer = input("answer number: ")
    
    try:
        answer_indice = int(answer) - 1
        if answer_indice < 0 or answer_indice >= len(options):
            print("invalid option.")
            return
        selected_option = list(options.keys())[answer_indice]
        
        clear_terminal()
        if options[selected_option]:
            print("correct! + 10 points.")
            points += 10
        else:
            print(f"wrong. -5 points")
            points -= 5

    except ValueError:
        print("invalid answer, please type the number which corresponds to the answer you want to choose.\n")

    time.sleep(1)  # pause for a second to let the user read the output

def main():
    global points

    clear_terminal()
    
    print("\nwelcome to my bkacup quiz game")
    print(f"\033[93m" + "\n<!> reminder that all questions were written with ai <!>\n" + "\033[0m")

    time.sleep(3)  # pause for a second to let the user read the welcome message

    for question in questions:
        options = questions[question]
        ask_question(question, options)
        handle_answer(question, options)


    clear_terminal()

    print(f"you scored {points} points out of {len(questions) * 10} possible points.\n")
    reply = input("would you like to play again? (y/n): ").strip().lower()
    if reply == 'y' or reply == 'yes':
        points = 0
        main()
    elif reply == 'n' or reply == 'no':
        clear_terminal()
    else:
        print("invalid input, exiting the game.")
        return
    
    print("thanks for playing! goodbye.")

main()
