import os 
import platform
import time

# questions generated by ai 🥱
questions = {
    "What is the capital of France?": {
        "Paris": True, # correct answers set to true.
        "Berlin": False,
        "Madrid": False,
        "Rome": False
    },
    "What is the largest planet in our solar system?": {
        "Earth": False,
        "Mars": False,
        "Jupiter": True,
        "Saturn": False
    },
    "What is the chemical symbol for water?": {
        "H2O": True,
        "CO2": False,
        "O2": False,
        "NaCl": False
    },
    "What is the main ingredient in guacamole?": {
        "Avocado": True,
        "Tomato": False,
        "Onion": False,
        "Pepper": False
    },
    "What is the smallest country in the world?": {
        "Vatican City": True,
        "Monaco": False,
        "San Marino": False,
        "Liechtenstein": False
    },
}


# points counter
points = 0

def clear_terminal(): # 🤤
    os.system(platform.system() == "Windows" and "cls" or "clear") # unix systems use the clear command, whereas windows uses cls

def ask_question(question, options: dict[str: bool]):
    clear_terminal()
    
    formatted_options = ""
    
    i = 0
    for a in options: # iterate over 
        formatted_options += f"{i + 1}. {a}\n" # iteration starts at 0, add one so it shows up starting from 1. 
        i += 1

    print("The question is:", question)
    print("Is it:\n" + formatted_options)

def handle_answer(_, options: dict[str: bool]):
    global points
    answer = input("answer number: ")
    
    try:
        answer_indice = int(answer) - 1 # arr index starts at one, refer to ask_question()
        if answer_indice < 0 or answer_indice >= len(options):
            print("invalid option.")
            return
        selected_option = list(options.keys())[answer_indice]
        
        clear_terminal()
        if options[selected_option]:
            print("correct! + 10 points.")
            points += 10
        else:
            print(f"wrong. -5 points")
            points -= 5

    except ValueError:
        print("invalid answer, please type the number which corresponds to the answer you want to choose.\n")

    time.sleep(1)  # pause for a second to let the user read the output

def main():
    global points # access global 'points'

    clear_terminal()
    
    # hi!!
    print("\nwelcome to my bkacup quiz game")
    print(f"\033[93m" + "\n<!> reminder that all questions were written with ai <!>\n" + "\033[0m")

    time.sleep(3)  # pause for a second to let the user read the welcome message

    # iterate over questions and ask one by one.
    for question in questions:
        options = questions[question]
        ask_question(question, options)
        handle_answer(question, options)

    clear_terminal()

    # 10 points per correct answer.
    print(f"you scored {points} points out of {len(questions) * 10} possible points.\n")
    reply = input("would you like to play again? (y/n): ").strip().lower()
    if reply == 'y' or reply == 'yes':
        points = 0
        main()
    elif reply == 'n' or reply == 'no':
        clear_terminal()
    else:
        print("thanks for playing! goodbye.")

main()
